# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53fb76c8d8f7c5585552e7a77fa4021ea0982af4787928b18133e1dfa874dac0abf374e200ce5a5891b7af47ce13f77fd3d8108dc1b61873513de785b86febcc

test:
  secret_key_base: 2f30ff3cad868d26edf3b5545acc4129091e4b0f93db8d4cf824ff65490c996cbd88c2fc1b2a93996cda1e12752e3729430f5d9fbb4d8431cdba834d10ff1688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
